"""Content creation tools — carousel and video generation for the agent."""

import json
import tempfile
from pathlib import Path

from langchain_core.tools import tool


@tool
async def create_carousel(
    topic: str,
    slides_content: str,
    theme: str = "dark",
    author: str = "",
) -> str:
    """Create an Instagram carousel (set of slide images with text).
    Use this when the user wants to create carousel content for social media.

    Args:
        topic: The topic/title of the carousel.
        slides_content: JSON string — a list of objects with 'title' and 'body' keys.
            Example: [{"title": "Tip 1", "body": "Wake up early..."}, ...]
        theme: Color theme: 'dark', 'light', 'gradient_blue', 'warm', 'green'.
        author: Instagram handle (without @) to show on slides.
    """
    try:
        slides_data = json.loads(slides_content)
    except json.JSONDecodeError:
        return "Error: slides_content must be valid JSON. Example: [{\"title\": \"...\", \"body\": \"...\"}]"

    if not isinstance(slides_data, list) or not slides_data:
        return "Error: slides_content must be a non-empty JSON array."

    from app.services.carousel import generate_carousel

    url = generate_carousel(slides_data=slides_data, theme=theme, author=author)
    return f"Carousel created! {len(slides_data)} slides. Download: {url}"


@tool
async def create_video_with_voiceover(
    script: str,
    voice_id: str = "",
    shuffle_clips: bool = True,
) -> str:
    """Create a video by combining the user's uploaded video clips with an
    AI-generated voiceover. The video clips are assembled randomly and the
    voiceover (generated by ElevenLabs) plays over them.

    Use this when the user wants to create a video with voiceover on a topic.
    The user must have previously uploaded video clips.

    Args:
        script: The text script for the voiceover narration.
        voice_id: ElevenLabs voice ID. Leave empty to use the user's default voice.
        shuffle_clips: Whether to randomize the order of video clips.
    """
    from app.services.elevenlabs import generate_speech
    from app.services.storage import list_user_videos
    from app.services.video import assemble_video

    # 1. Check for uploaded videos
    videos = list_user_videos()
    if not videos:
        return "Error: No video clips found. Please upload video clips first via the upload endpoint."

    video_keys = [v["key"] for v in videos]

    # 2. Generate voiceover
    try:
        audio_bytes = await generate_speech(text=script, voice_id=voice_id or None)
    except ValueError as e:
        return f"Error: {e}"
    except Exception as e:
        return f"Error generating voiceover: {e}"

    # 3. Save audio to temp file
    with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as f:
        f.write(audio_bytes)
        audio_path = f.name

    # 4. Assemble video
    try:
        video_url = await assemble_video(
            video_keys=video_keys,
            audio_path=audio_path,
            shuffle=shuffle_clips,
        )
    except Exception as e:
        return f"Error assembling video: {e}"
    finally:
        Path(audio_path).unlink(missing_ok=True)

    return f"Video created! Download: {video_url}"


@tool
async def list_uploaded_videos() -> str:
    """List all video clips the user has uploaded. Use this to check
    what clips are available before creating a video."""
    from app.services.storage import list_user_videos

    videos = list_user_videos()
    if not videos:
        return "No videos uploaded yet. Upload clips via POST /api/upload/video."

    lines = [f"Found {len(videos)} video clip(s):"]
    for v in videos:
        size_mb = v["size"] / (1024 * 1024)
        lines.append(f"  - {v['key']} ({size_mb:.1f} MB)")
    return "\n".join(lines)


@tool
async def list_available_voices() -> str:
    """List available ElevenLabs voices. Use this when the user wants
    to see what voices they can use for voiceover."""
    from app.services.elevenlabs import list_voices

    voices = await list_voices()
    if not voices:
        return "No voices available. Make sure ELEVENLABS_API_KEY is configured."

    lines = [f"Available voices ({len(voices)}):"]
    for v in voices:
        lines.append(f"  - {v['name']} (ID: {v['voice_id']}, category: {v['category']})")
    return "\n".join(lines)
